ReceptiIspodSunca/urls.py
from django.contrib import admin
from django.urls import path, include
from main.forms import register 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

main/urls.py
from django.urls import path
from . import views
from .views import *

from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('all_recipes', views.all_recipes, name='all_recipes'),
    path('user_recipes', views.user_recipes, name='user_recipes'),
    path('edit_recipe/<int:recipe_id>/', user_edit_recipe, name='user_edit_recipe'),
    path('delete_recipe/<int:recipe_id>/', user_delete_recipe, name='user_delete_recipe'),
    path('write_a_recipe', views.write_a_recipe, name='write_a_recipe'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

# Create your models here.
# class Equipment(models.Model):
#     name = models.CharField(max_length=64, unique=True)

#     def __str__(self):
#         return self.name
    
# class Ingredient(models.Model):
#     name = models.CharField(max_length=64, unique=True)

#     def __str__(self):
#         return self.name

class Recipe(models.Model):
    name = models.CharField(max_length=64, unique=True)

    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    # numberOfSaves = models.IntegerField(default=0)

    CATEGORIES = (
        ('food', 'Hrana'),
        ('drink', 'Piće'),
        ('medicine', 'Lijek'),
    )
    category = models.CharField(max_length=8, choices=CATEGORIES, default='food')

    equipment = models.TextField(default="")
    ingredients = models.TextField(default="")
    time_needed = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    TIME_UNITS = (
        ('min', 'min'),
        ('ura', 'h'),
        ('dan', 'dan'),
    )
    time_measurement_unit = models.CharField(max_length=8, choices=TIME_UNITS, default='min')

    preperation = models.TextField(default="")

    def __str__(self):
        return '„' + str(self.name) + '“' + ', autor: ' + str(self.author)

main/forms.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render

from django import forms
from .models import *

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            # Authenticate the user
            user = authenticate(request, username=username, password=password)
            if user is not None:
                # Log the user in
                login(request, user)
                return redirect('main:homepage')  # Assuming 'homepage' is the name of your homepage URL pattern
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'category', 'equipment', 'ingredients', 'time_needed', 'time_measurement_unit', 'preperation']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import Recipe
from .forms import RecipeForm

## Create your views here.
def all_recipes(request):
    search_query = request.GET.get('search_query', '')
    category = request.GET.get('category', '')

    recipes = Recipe.objects.all()

    if search_query:
        recipes = recipes.filter(name__icontains=search_query)

    if category:
        recipes = recipes.filter(category=category)

    context = {
        'filtered_recipes': recipes
    }
    
    return render(request, 'main/all_recipes.html', context)

def user_recipes(request):
    search_query = request.GET.get('search_query', '')
    category = request.GET.get('category', '')

    recipes = Recipe.objects.filter(author=request.user)

    if search_query:
        recipes = recipes.filter(name__icontains=search_query)

    if category:
        recipes = recipes.filter(category=category)

    context = {
        'filtered_recipes': recipes,
    }

    return render(request, 'main/user_recipes.html', context)

def user_edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id, author=request.user)
    
    if request.method == 'POST':
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('main:user_recipes')
    else:
        form = RecipeForm(instance=recipe)
    
    context = {
        'form': form,
    }
    return render(request, 'main/user_edit_recipe.html', context)

def user_delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id, author=request.user)
    recipe.delete()
    return redirect('main:user_recipes')

def write_a_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            # Check if the user is authenticated
            if request.user.is_authenticated:
                # Assign the logged-in user as the author of the recipe
                author = request.user
            else:
                # If the user is not logged in, set the author to "Anonymous"
                author = None  # Or None
            # Save the recipe with the appropriate author
            recipe = form.save(commit=False)
            recipe.author = author
            recipe.save()
            return redirect(reverse('main:user_recipes'))  # Redirect to a page displaying a list of the users' recipes
    else:
        form = RecipeForm()
    return render(request, 'main/write_a_recipe.html', {'form': form})

def recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    return render(request, 'main/recipe.html', {'recipe': recipe})

templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recepti Ispod Sunca</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=1">
    <link rel="icon" href="{% static 'images/favicon.ico' %}?v=1" type="image/x-icon">
</head>
<body>
    <header>
        <div id="authentification">
            {% if user.is_authenticated %}
            <p>Prijavljeni korisnik:&nbsp;</p>
            <p>{{ user.username }}</p>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Odjavite se">
            </form>
            {% else %}
                <nav>
                    <ul>
                        <li><a href="{% url 'login' %}">Prijava</a></li>
                        <li><a href="{% url 'register' %}">Registracija</a></li>
                    </ul>
                </nav>
            {% endif %}
        </div>
        <h1>Recepti Ispod Sunca</h1>
        <nav>
            <ul>
                <li><a href="{% url 'main:all_recipes' %}" class="{% if request.path == '/main/all_recipes' %}active{% endif %}">Svi Recepti</a></li>
                <li><a href="{% url 'main:user_recipes' %}" class="{% if request.path == '/main/user_recipes' %}active{% endif %}">Korisnikovi Recepti</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>
        <h3>Propovjednik 1:9</h3>
        <p><i>„Što je bilo, opet će biti, i što se činilo, opet će se činiti, i nema ništa novo pod suncem.“</i></p>
    </footer>
    <script src="{% static 'js/script.js' %}?v=1"></script>
</body>
</html>

templates/main/all_recipes.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Svi Recepti</h2>
    <form method="GET" class="form-group">
        <input type="text" name="search_query" placeholder="Naziv recepta..." value="{{ request.GET.search_query }}">
        <select name="category">
            <option value="">Sve kategorije</option>
            <option value="drink" {% if request.GET.category == "drink" %}selected{% endif %}>Piće</option>
            <option value="food" {% if request.GET.category == "food" %}selected{% endif %}>Hrana</option>
            <option value="medicine" {% if request.GET.category == "medicine" %}selected{% endif %}>Lijek</option>
        </select>
        <button type="submit">Pretraži</button>
    </form>
    <hr>
    <div class="recipe-list">
        <ul>
            {% for recipe in filtered_recipes %}
                <li>
                    <a href="{% url 'main:recipe' recipe.id %}" class="non-btn">„{{ recipe.name }}“</a>&nbsp; ~ {{ recipe.author }}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/main/recipe.html
{% extends "base_generic.html" %}

{% block content %}
    <button>
        <a href="/main/all_recipes">Natrag</a>
    </button>
    <div class="recipe" id="recipe" data-recipe-name="{{ recipe.name }}">
        <h3 class="flex-center">„{{ recipe.name }}“</h3>
        <p>
            <strong>Autor:&nbsp;</strong>
            <i>{{ recipe.author.username }}</i>
        </p>
        <p>
            <strong>Kategorija:&nbsp;</strong>
            {{ recipe.get_category_display }}
        </p>
        <p>
            <strong>Oprema:&nbsp;</strong>
            {{ recipe.equipment }}
        </p>
        <p>
            <strong>Sastojci:&nbsp;</strong>
            {{ recipe.ingredients }}
        </p>
        <p>
            <strong>Potrebno vrijeme:&nbsp;</strong>
            {{ recipe.time_needed }}
            {{ recipe.get_time_measurement_unit_display }}
        </p>
        <p>
            <strong>Priprema:</strong>
        </p>
        <p>
            {{ recipe.preperation }}
        </p>
    </div>
    <div class="center-btn">
        <button onclick="downloadRecipeAsText()">Preuzmi recept</button>
    </div>
{% endblock %}

templates/main/user_edit_recipe.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Uredi recept</h2>
    <div class="recipe">
        <form method="post" class="recipe-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Naziv:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_category">Kategorija:</label>
                {{ form.category }}
            </div>
            <div class="form-group">
                <label for="id_equipment">Oprema:</label>
                {{ form.equipment }}
            </div>
            <div class="form-group">
                <label for="id_ingredients">Sastojci:</label>
                {{ form.ingredients }}
            </div>
            <div class="form-group">
                <label for="{{ form.time_needed.id_for_label }}">Vrijeme potrebno za pripremu:</label>
                {{ form.time_needed }}
                <label for="{{ form.time_measurement_unit.id_for_label }}"></label>
                {{ form.time_measurement_unit }}
            </div>
            <div class="form-group">
                <label for="id_preperation">Priprema:</label>
                {{ form.preperation }}
            </div>
            <div class="flex-center">
                <button type="submit" class="btn btn-primary">Spremi promjene</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/main/user_recipes.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Korisnikovi Recepti</h2>
    {% if user.is_authenticated %}
        <div>
            <button>
                <a href="/main/write_a_recipe">Napiši recept</a>
            </button>
        </div>
        <form method="GET" class="form-group">
            <input type="text" name="search_query" placeholder="Naziv recepta..." value="{{ request.GET.search_query }}">
            <select name="category">
                <option value="">Sve kategorije</option>
                <option value="drink" {% if request.GET.category == "drink" %}selected{% endif %}>Piće</option>
                <option value="food" {% if request.GET.category == "food" %}selected{% endif %}>Hrana</option>
                <option value="medicine" {% if request.GET.category == "medicine" %}selected{% endif %}>Lijek</option>
            </select>
            <button type="submit">Pretraži</button>
        </form>
        <hr>
        <div class="recipe-list">
            <ul>
                {% for recipe in filtered_recipes %}
                    <li>
                        <a href="{% url 'main:recipe' recipe.id %}" class="non-btn">„{{ recipe.name }}“</a>&nbsp;
                        <a href="{% url 'main:user_edit_recipe' recipe.id %}" class="btn btn-primary"><button>Uredi</button></a>
                        <a href="{% url 'main:user_delete_recipe' recipe.id %}" class="btn btn-primary delete-btn" data-url="{% url 'main:user_delete_recipe' recipe.id %}"><button>Pobriši</button></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>Niste prijavljeni!</p>
        <p><button><a href="/accounts/login">Prijavite se</a></button> kako biste vidjeli svoje recepte.</p>
    {% endif %}
{% endblock %}

templates/main/write_a_recipe.html
{% extends "base_generic.html" %}
{% block content %}
    <button>
        <a href="user_recipes">Odustani</a>
    </button>
    <h3>Napiši Recept</h3>
    <div class="recipe">
        <form method="post" class="recipe-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Naziv:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.category.id_for_label }}">Kategorija:</label>
                {{ form.category }}
            </div>
            <div class="form-group">
                <label for="{{ form.equipment.id_for_label }}">Oprema:</label>
                {{ form.equipment }}
            </div>
            <div class="form-group">
                <label for="{{ form.ingredients.id_for_label }}">Sastojci:</label>
                {{ form.ingredients }}
            </div>
            <div class="form-group">
                <label for="{{ form.time_needed.id_for_label }}">Vrijeme potrebno za pripremu:</label>
                {{ form.time_needed }}
                <label for="{{ form.time_measurement_unit.id_for_label }}"></label>
                {{ form.time_measurement_unit }}
            </div>
            <div class="form-group">
                <label for="{{ form.preperation.id_for_label }}">Priprema:</label>
                {{ form.preperation }}
            </div>
            <div class="flex-center">
                <button type="submit" class="btn btn-primary" onclick="validateForm()">Spremi recept</button>
            </div>
        </form>
    </div>
    <script>
        function validateForm() {
            var timeNeeded = document.getElementById("id_time_needed").value;
            if (isNaN(timeNeeded) || timeNeeded <= 0) {
                alert("Vrijeme potrebno za pripremu mora biti pozitivan broj.");
            } else {
                document.getElementById("recipe-writing-form").submit(); // Submit the form if validation passes
            }
        }
    </script>
{% endblock %}